"""add review embedding

Revision ID: 26b0f8cc1e0e
Revises: 2afe4fac211d
Create Date: 2026-08-12 21:20:39.730822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "26b0f8cc1e0e"
down_revision: Union[str, Sequence[str], None] = "2afe4fac211d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews",
        sa.Column(
            "embedding",
            Vector(384),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "embedding")
    # ### end Alembic commands ###
